# Generated by Django 3.2.4 on 2021-07-27 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20210727_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='/products/placeholder.png', upload_to='products/'),
        ),
    ]
