# Generated by Django 3.2.4 on 2021-07-27 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='mernshop/products/placeholder.png', upload_to='products/'),
        ),
    ]
