export const GET_ALL_PRODUCTS_REQUEST = "GET_ALL_PRODUCTS_REQUEST";
export const GET_ALL_PRODUCTS_SUCCESS = "GET_ALL_PRODUCTS_SUCCESS";
export const GET_ALL_PRODUCTS_FAIL = "GET_ALL_PRODUCTS_FAIL";

export const GET_PRODUCT_BYID_REQUEST = "GET_PRODUCT_BYID_REQUEST";
export const GET_PRODUCT_BYID_SUCCESS = "GET_PRODUCT_BYID_SUCCESS";
export const GET_PRODUCT_BYID_FAIL = "GET_PRODUCT_BYID_FAIL";
export const GET_PRODUCT_BYID_RESET = "GET_PRODUCT_BYID_RESET";

export const ADD_TOCART_ITEM = "ADD_TOCART_ITEM";
export const REMOVE_FROMCART_ITEM = "REMOVE_FROMCART_ITEM";
export const CLEAR_SUCCESS = "CLEAR_SUCCESS";
